name: build

on:
  push:
    paths-ignore:
      - README.org

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo apt-get update
      - run: sudo apt-get -y install --no-install-recommends libupower-glib-dev libpq5 xorg-dev
      - run: make
